### PR TITLE
Added light/dark theme switcher

### PR DESCRIPTION
**Pull request by Aybee5**
Added an icon for changing the theme and on click it changes some elements styling.
I named the light-theme 'not-dark' because, when the application is loaded, the default dark-theme is named as 'light-theme'.

### CODE REVIEW

**Review by astagi — CHANGES_REQUESTED** [review]
Thanks for the PR! The darkmode/lightmode switcher would be put globally next to the "BETA" label, and I would change the icon with something like this https://codepen.io/nathangath/pen/qYeOJJ

**Comment by Aybee5** [comment]
Hello @astagi, what's the update concerning this? should I implement the changes you requested?

**Comment by astagi** [comment]
> Hello @astagi, what's the update concerning this? should I implement the changes you requested?

Hi @Aybee5 sorry for my late response! Yes please, add the light/dark theme switch globally and please use a prettier icon like the example I linked in my previous comment :) If you need help let me know!

**Comment by Aybee5** [comment]
Hello @astagi I've implemented all the changes requested

**Review by astagi — APPROVED** [review]

**Comment by astagi** [comment]
It looks awesome @Aybee5 thanks a lot! ❤️

**Comment by Aybee5** [comment]
Thank you for accepting my PR 😄

**Pull request merged**
